services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastify-prisma
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/posgresql/data

volumes:
  postgres-data:
    driver: local